version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    container_name: shopping_list-postgres
    image: postgres:15-alpine
    #        labels:
    #            com.symfony.server.service-prefix: 'DATABASE'
    environment:
      POSTGRES_DB: shopping_list
      POSTGRES_USER: shopping_list
      POSTGRES_PASSWORD: devpass
      PGDATA: /var/lib/postgresql/data/shopping_list_sql
    ports:
      - "15432:5432"
    volumes:
      - ${PWD}/../data/postgres:/var/lib/postgresql/data:rw

#  database:
#    container_name: postgres
#    image: postgres:latest
#    environment:
#      POSTGRES_DB: shopping_list
#      # You should definitely change the password in production
#      POSTGRES_PASSWORD: devpass
#      POSTGRES_USER: shopping_list
#    ports:
#      - "3306:3306"
#    volumes:
#      - ${PWD}/../data/postgres:/var/lib/postgresql

      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw

  mailcatcher:
    container_name: mailcatcher
    image: schickling/mailcatcher
    ports:
      - "1025:1025"
      - "1080:1080"